document.write('<!DOCTYPE html>');
document.write('<html lang="en">');
document.write('<head>');
document.write('    <title>dc.js - Box Plot Example</title>');
document.write('    <meta charset="UTF-8">');
document.write('    <link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">');
document.write('    <link rel="stylesheet" type="text/css" href="../css/dc.css"/>');
document.write('    <link type="text/css" rel="stylesheet" href="../css/dc-floatleft.css"/>');
document.write('</head>');
document.write('<body>');
document.write('');
document.write('<div class="container">');
document.write('<script type="text/javascript" src="header.js"></script>');
document.write('<div id="box-test"></div>');
document.write('<div id="pie-chart"></div>');
document.write('');
document.write('<script type="text/javascript" src="../js/d3.js"></script>');
document.write('<script type="text/javascript" src="../js/crossfilter.js"></script>');
document.write('<script type="text/javascript" src="../js/dc.js"></script>');
document.write('<script type="text/javascript">');
document.write('');
document.write('var chart = dc.boxPlot("#box-test"),');
document.write('    pie = new dc.PieChart("#pie-chart");');
document.write('d3.csv("morley.csv").then(function(experiments) {');
document.write('');
document.write('  experiments.forEach(function(x) {');
document.write('    x.Speed = +x.Speed;');
document.write('  });');
document.write('');
document.write('  var ndx                 = crossfilter(experiments),');
document.write('      runDimension        = ndx.dimension(function(d) {return +d.Run;}),');
document.write('      runGroup            = runDimension.group(),');
document.write('      experimentDimension = ndx.dimension(function(d) {return "exp-" + d.Expt;}),');
document.write('      speedArrayGroup     = experimentDimension.group().reduce(');
document.write('        function(p,v) {');
document.write('          // keep array sorted for efficiency');
document.write('          p.splice(d3.bisectLeft(p, v.Speed), 0, v.Speed);');
document.write('          return p;');
document.write('        },');
document.write('        function(p,v) {');
document.write('          p.splice(d3.bisectLeft(p, v.Speed), 1);');
document.write('          return p;');
document.write('        },');
document.write('        function() {');
document.write('          return [];');
document.write('        }');
document.write('      );');
document.write('');
document.write('  chart');
document.write('    .width(768)');
document.write('    .height(480)');
document.write('    .margins({top: 10, right: 50, bottom: 30, left: 50})');
document.write('    .dimension(experimentDimension)');
document.write('    .group(speedArrayGroup)');
document.write('    .elasticY(true)');
document.write('    .elasticX(true);');
document.write('');
document.write('  pie');
document.write('    .width(140)');
document.write('    .height(140)');
document.write('    .radius(70)');
document.write('    .dimension(runDimension)');
document.write('    .group(runGroup);');
document.write('');
document.write('  dc.renderAll();');
document.write('/*');
document.write('  var i=0;');
document.write('  setInterval(function() {');
document.write('    runDimension.filterAll();');
document.write('    runDimension.filter([i++,21]);');
document.write('    dc.renderAll();');
document.write('  }, 2000);');
document.write('*/');
document.write('});');
document.write('');
document.write('</script>');
document.write('');
document.write('</div>');
document.write('</body>');
document.write('</html>');
